/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailableAddonsRequest {
    #[serde(rename = "tariffs")]
    pub tariffs: Vec<String>,
    #[serde(rename = "routeSections")]
    pub route_sections: Vec<models::RouteSectionRequest>,
    #[serde(rename = "ticketId", skip_serializing_if = "Option::is_none")]
    pub ticket_id: Option<i64>,
}

impl AvailableAddonsRequest {
    pub fn new(
        tariffs: Vec<String>,
        route_sections: Vec<models::RouteSectionRequest>,
    ) -> AvailableAddonsRequest {
        AvailableAddonsRequest {
            tariffs,
            route_sections,
            ticket_id: None,
        }
    }
}
