/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreditAddRequest : User registered account credit charge request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditAddRequest {
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "paymentMethodCode")]
    pub payment_method_code: String,
    #[serde(rename = "correlationId")]
    pub correlation_id: String,
    #[serde(rename = "formFields")]
    pub form_fields: Vec<models::PaymentFormFieldValue>,
    #[serde(rename = "rememberCard", skip_serializing_if = "Option::is_none")]
    pub remember_card: Option<bool>,
}

impl CreditAddRequest {
    /// User registered account credit charge request
    pub fn new(
        amount: f64,
        currency: models::Currency,
        payment_method_code: String,
        correlation_id: String,
        form_fields: Vec<models::PaymentFormFieldValue>,
    ) -> CreditAddRequest {
        CreditAddRequest {
            amount,
            currency,
            payment_method_code,
            correlation_id,
            form_fields,
            remember_card: None,
        }
    }
}
