/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepartureConnection {
    /// ID of the connection
    #[serde(rename = "connectionId", skip_serializing_if = "Option::is_none")]
    pub connection_id: Option<i64>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    /// Information about the delay in minutes on a given connection
    #[serde(rename = "delay", skip_serializing_if = "Option::is_none")]
    pub delay: Option<i32>,
    #[serde(rename = "vehicleCategory", skip_serializing_if = "Option::is_none")]
    pub vehicle_category: Option<models::VehicleCategory>,
    #[serde(rename = "freeSeatCount", skip_serializing_if = "Option::is_none")]
    pub free_seat_count: Option<i32>,
    /// Individual stations (including metadata) sort according to order which connection builds.
    #[serde(rename = "stations", skip_serializing_if = "Option::is_none")]
    pub stations: Option<Vec<models::DepartureConnectionStation>>,
    /// Vehicle standard code.
    #[serde(rename = "vehicleStandard", skip_serializing_if = "Option::is_none")]
    pub vehicle_standard: Option<VehicleStandard>,
}

impl DepartureConnection {
    pub fn new() -> DepartureConnection {
        DepartureConnection {
            connection_id: None,
            label: None,
            number: None,
            delay: None,
            vehicle_category: None,
            free_seat_count: None,
            stations: None,
            vehicle_standard: None,
        }
    }
}
/// Vehicle standard code.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum VehicleStandard {
    #[serde(rename = "YELLOW")]
    #[default]
    Yellow,
    #[serde(rename = "YELLOW_R8")]
    YellowR8,
    #[serde(rename = "ECONOMY")]
    Economy,
    #[serde(rename = "FUN_RELAX")]
    FunRelax,
    #[serde(rename = "FUN_RELAX_SELF_SERVICE")]
    FunRelaxSelfService,
    #[serde(rename = "FUN_RELAX_NO_STEWARD")]
    FunRelaxNoSteward,
    #[serde(rename = "DEUTSCHE_BAHN")]
    DeutscheBahn,
    #[serde(rename = "ECONOMY_PLATFORM")]
    EconomyPlatform,
    #[serde(rename = "RESTAURANT")]
    Restaurant,
    #[serde(rename = "SAD")]
    Sad,
    #[serde(rename = "WEST_BAHN")]
    WestBahn,
    #[serde(rename = "IDS_JMK")]
    IdsJmk,
    #[serde(rename = "OBB")]
    Obb,
    #[serde(rename = "UKRAINIAN_RAILWAYS")]
    UkrainianRailways,
}
