/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Discount {
    #[serde(rename = "id")]
    pub id: i64,
    /// Percentual discount size
    #[serde(rename = "percentage")]
    pub percentage: i32,
    /// Maximal number of passengers
    #[serde(rename = "passengers")]
    pub passengers: i32,
    /// Country code value (see endpoint GET /consts/locations)
    #[serde(rename = "fromCountry", skip_serializing_if = "Option::is_none")]
    pub from_country: Option<String>,
    /// ID of the City from fromCountry (see endpoint GET /consts/locations)
    #[serde(rename = "fromCityId", skip_serializing_if = "Option::is_none")]
    pub from_city_id: Option<i64>,
    /// ID of the Station from fromCity (see endpoint GET /consts/locations)
    #[serde(rename = "fromStationId", skip_serializing_if = "Option::is_none")]
    pub from_station_id: Option<i64>,
    /// ID of the City from toCountry (see endpoint GET /consts/locations)
    #[serde(rename = "toCountry", skip_serializing_if = "Option::is_none")]
    pub to_country: Option<String>,
    /// City ID (see endpoint GET /consts/locations)
    #[serde(rename = "toCityId", skip_serializing_if = "Option::is_none")]
    pub to_city_id: Option<i64>,
    /// ID of the Station from toCity (see endpoint GET /consts/locations)
    #[serde(rename = "toStationId", skip_serializing_if = "Option::is_none")]
    pub to_station_id: Option<i64>,
    #[serde(rename = "dateFrom", skip_serializing_if = "Option::is_none")]
    pub date_from: Option<String>,
    #[serde(rename = "dateTo", skip_serializing_if = "Option::is_none")]
    pub date_to: Option<String>,
    #[serde(rename = "state")]
    pub state: models::DiscountState,
    /// If there is used discount there is as well ticket ID which is linked to it.
    #[serde(rename = "ticketId", skip_serializing_if = "Option::is_none")]
    pub ticket_id: Option<i64>,
}

impl Discount {
    pub fn new(
        id: i64,
        percentage: i32,
        passengers: i32,
        state: models::DiscountState,
    ) -> Discount {
        Discount {
            id,
            percentage,
            passengers,
            from_country: None,
            from_city_id: None,
            from_station_id: None,
            to_country: None,
            to_city_id: None,
            to_station_id: None,
            date_from: None,
            date_to: None,
            state,
            ticket_id: None,
        }
    }
}
