/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum GroupCapability {
    #[serde(rename = "INTERSTATE_SALE")]
    #[default]
    InterstateSale,
    #[serde(rename = "DOMESTIC_SALE_CZ")]
    DomesticSaleCz,
    #[serde(rename = "DOMESTIC_SALE_SK")]
    DomesticSaleSk,
    #[serde(rename = "LIMITED_SALE")]
    LimitedSale,
    #[serde(rename = "CUSTOMER_CARD_SALE")]
    CustomerCardSale,
    #[serde(rename = "COMPENSATIONS")]
    Compensations,
    #[serde(rename = "PAYMENT_CARD")]
    PaymentCard,
    #[serde(rename = "EUR_PAYMENT")]
    EurPayment,
    #[serde(rename = "DEUTSCHE_BAHN_TICKETS")]
    DeutscheBahnTickets,
}

impl std::fmt::Display for GroupCapability {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InterstateSale => write!(f, "INTERSTATE_SALE"),
            Self::DomesticSaleCz => write!(f, "DOMESTIC_SALE_CZ"),
            Self::DomesticSaleSk => write!(f, "DOMESTIC_SALE_SK"),
            Self::LimitedSale => write!(f, "LIMITED_SALE"),
            Self::CustomerCardSale => write!(f, "CUSTOMER_CARD_SALE"),
            Self::Compensations => write!(f, "COMPENSATIONS"),
            Self::PaymentCard => write!(f, "PAYMENT_CARD"),
            Self::EurPayment => write!(f, "EUR_PAYMENT"),
            Self::DeutscheBahnTickets => write!(f, "DEUTSCHE_BAHN_TICKETS"),
        }
    }
}
