/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentType : Payment method category
/// Payment method category
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentType {
    #[serde(rename = "ONLINE")]
    #[default]
    Online,
    #[serde(rename = "CASH")]
    Cash,
    #[serde(rename = "TRANSFER")]
    Transfer,
    #[serde(rename = "GIFT")]
    Gift,
}

impl std::fmt::Display for PaymentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Online => write!(f, "ONLINE"),
            Self::Cash => write!(f, "CASH"),
            Self::Transfer => write!(f, "TRANSFER"),
            Self::Gift => write!(f, "GIFT"),
        }
    }
}
