/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Payment {
    #[serde(rename = "paymentId")]
    pub payment_id: i64,
    #[serde(rename = "ticketId", skip_serializing_if = "Option::is_none")]
    pub ticket_id: Option<i64>,
    #[serde(rename = "ticketType", skip_serializing_if = "Option::is_none")]
    pub ticket_type: Option<models::PaymentTicketType>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "method")]
    pub method: models::TransactionMethod,
    #[serde(rename = "dateTransaction")]
    pub date_transaction: String,
    #[serde(rename = "isReceiptAvailable")]
    pub is_receipt_available: bool,
    #[serde(rename = "isInvoiceAvailable")]
    pub is_invoice_available: bool,
}

impl Payment {
    pub fn new(
        payment_id: i64,
        amount: f64,
        currency: models::Currency,
        method: models::TransactionMethod,
        date_transaction: String,
        is_receipt_available: bool,
        is_invoice_available: bool,
    ) -> Payment {
        Payment {
            payment_id,
            ticket_id: None,
            ticket_type: None,
            description: None,
            amount,
            currency,
            method,
            date_transaction,
            is_receipt_available,
            is_invoice_available,
        }
    }
}
