/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentSettingsResponse {
    /// Nastaveni zapamatovane karty
    #[serde(rename = "rememberCard")]
    pub remember_card: bool,
    /// Posledni provedena platebni metoda
    #[serde(rename = "lastPaymentType")]
    pub last_payment_type: String,
}

impl PaymentSettingsResponse {
    pub fn new(remember_card: bool, last_payment_type: String) -> PaymentSettingsResponse {
        PaymentSettingsResponse {
            remember_card,
            last_payment_type,
        }
    }
}
