/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QrCodeAccount {
    /// Version of QR code
    #[serde(rename = "qrCodeVersion", skip_serializing_if = "Option::is_none")]
    pub qr_code_version: Option<i32>,
    #[serde(rename = "qrCodeAccountType", skip_serializing_if = "Option::is_none")]
    pub qr_code_account_type: Option<models::QrCodeAccountType>,
    /// Code of account
    #[serde(rename = "accountCode", skip_serializing_if = "Option::is_none")]
    pub account_code: Option<String>,
    /// First name of passenger
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Surname of passenger
    #[serde(rename = "surname", skip_serializing_if = "Option::is_none")]
    pub surname: Option<String>,
    /// Default tariff of account
    #[serde(rename = "tariff", skip_serializing_if = "Option::is_none")]
    pub tariff: Option<String>,
    /// Default currency of account
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
}

impl QrCodeAccount {
    pub fn new() -> QrCodeAccount {
        QrCodeAccount {
            qr_code_version: None,
            qr_code_account_type: None,
            account_code: None,
            name: None,
            surname: None,
            tariff: None,
            currency: None,
        }
    }
}
