/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteSeatsResponse {
    #[serde(rename = "sectionId")]
    pub section_id: i64,
    /// TRUE => seat reservation; FALSE => seat choosed while boarding
    #[serde(rename = "fixedSeatReservation")]
    pub fixed_seat_reservation: bool,
    #[serde(rename = "vehicles", skip_serializing_if = "Option::is_none")]
    pub vehicles: Option<Vec<models::Vehicle>>,
    #[serde(rename = "selectedSeats", skip_serializing_if = "Option::is_none")]
    pub selected_seats: Option<Vec<models::SelectedSeat>>,
}

impl RouteSeatsResponse {
    pub fn new(section_id: i64, fixed_seat_reservation: bool) -> RouteSeatsResponse {
        RouteSeatsResponse {
            section_id,
            fixed_seat_reservation,
            vehicles: None,
            selected_seats: None,
        }
    }
}
