/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteSeatsRequest100 {
    #[serde(rename = "sections")]
    pub sections: Vec<models::SimpleSection>,
    #[serde(rename = "tariffs", skip_serializing_if = "Option::is_none")]
    pub tariffs: Option<Vec<String>>,
    #[serde(rename = "seatClass", skip_serializing_if = "Option::is_none")]
    pub seat_class: Option<String>,
}

impl RouteSeatsRequest100 {
    pub fn new(sections: Vec<models::SimpleSection>) -> RouteSeatsRequest100 {
        RouteSeatsRequest100 {
            sections,
            tariffs: None,
            seat_class: None,
        }
    }
}
