/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteSectionRequest {
    #[serde(rename = "sectionId")]
    pub section_id: i64,
    #[serde(rename = "departureStationId")]
    pub departure_station_id: i64,
    #[serde(rename = "arrivalStationId")]
    pub arrival_station_id: i64,
    #[serde(rename = "selectedSeats", skip_serializing_if = "Option::is_none")]
    pub selected_seats: Option<Vec<models::SelectedSeat100>>,
}

impl RouteSectionRequest {
    pub fn new(
        section_id: i64,
        departure_station_id: i64,
        arrival_station_id: i64,
    ) -> RouteSectionRequest {
        RouteSectionRequest {
            section_id,
            departure_station_id,
            arrival_station_id,
            selected_seats: None,
        }
    }
}
