/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SroCancelCharge {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "percent")]
    pub percent: i32,
}

impl SroCancelCharge {
    pub fn new(message: String, amount: f64, currency: String, percent: i32) -> SroCancelCharge {
        SroCancelCharge {
            message,
            amount,
            currency,
            percent,
        }
    }
}
