/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SroTicket {
    #[serde(rename = "sroTicketId")]
    pub sro_ticket_id: i64,
    /// Final price for ticket, addons etc.
    #[serde(rename = "price")]
    pub price: f64,
    /// Final price to be paid
    #[serde(rename = "unpaid")]
    pub unpaid: f64,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "state")]
    pub state: models::TicketState,
    #[serde(rename = "seatClassKey")]
    pub seat_class_key: String,
    #[serde(rename = "conditions")]
    pub conditions: Box<models::SroConditions>,
    #[serde(rename = "customerActions")]
    pub customer_actions: Box<models::CustomerActions>,
    #[serde(rename = "routeSections")]
    pub route_sections: Vec<models::TicketSection>,
    /// Payment ID (groupTransactionID). Available only with paid ticket. Necessary for further action with ticket (for example: print invoice)
    #[serde(rename = "paymentId")]
    pub payment_id: i64,
    #[serde(rename = "bills")]
    pub bills: Vec<models::SroTicketBill>,
    #[serde(rename = "passengersInfo")]
    pub passengers_info: Box<models::SroTicketPassenger>,
    /// Textual information about the first delay on the route
    #[serde(rename = "delay")]
    pub delay: String,
    /// Textual information about the travel time on a given section
    #[serde(rename = "travelTime")]
    pub travel_time: String,
    /// Estimated arrival date time (arrival + delay)
    #[serde(rename = "estimatedArrivalTime")]
    pub estimated_arrival_time: String,
    /// Returns true in case the ticket was crited by affiliate partner.
    #[serde(rename = "affiliateTicket")]
    pub affiliate_ticket: bool,
}

impl SroTicket {
    pub fn new(
        sro_ticket_id: i64,
        price: f64,
        unpaid: f64,
        currency: models::Currency,
        state: models::TicketState,
        seat_class_key: String,
        conditions: models::SroConditions,
        customer_actions: models::CustomerActions,
        route_sections: Vec<models::TicketSection>,
        payment_id: i64,
        bills: Vec<models::SroTicketBill>,
        passengers_info: models::SroTicketPassenger,
        delay: String,
        travel_time: String,
        estimated_arrival_time: String,
        affiliate_ticket: bool,
    ) -> SroTicket {
        SroTicket {
            sro_ticket_id,
            price,
            unpaid,
            currency,
            state,
            seat_class_key,
            conditions: Box::new(conditions),
            customer_actions: Box::new(customer_actions),
            route_sections,
            payment_id,
            bills,
            passengers_info: Box::new(passengers_info),
            delay,
            travel_time,
            estimated_arrival_time,
            affiliate_ticket,
        }
    }
}
