/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SroRoute {
    /// {section0.id},{section1.id}, ...
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "departureStationId")]
    pub departure_station_id: i64,
    #[serde(rename = "departureTime")]
    pub departure_time: String,
    #[serde(rename = "arrivalStationId", skip_serializing_if = "Option::is_none")]
    pub arrival_station_id: Option<i64>,
    #[serde(rename = "arrivalTime")]
    pub arrival_time: String,
    /// Vehicle types (for example: train, bus)
    #[serde(rename = "vehicleTypes")]
    pub vehicle_types: Vec<models::VehicleType>,
    /// Number of transfers
    #[serde(rename = "transfersCount", skip_serializing_if = "Option::is_none")]
    pub transfers_count: Option<i32>,
    /// Lowest found price.
    #[serde(rename = "priceFrom")]
    pub price_from: f64,
    /// Highest found price.
    #[serde(rename = "priceTo")]
    pub price_to: f64,
    /// Overall number of found prices.
    #[serde(rename = "pricesCount", skip_serializing_if = "Option::is_none")]
    pub prices_count: Option<i32>,
    /// Notice of any extraordinarily events on route / traffic limitation
    #[serde(rename = "notices")]
    pub notices: bool,
    /// TRUE if this line (or its part) have support connection, otherwise FALSE
    #[serde(rename = "support")]
    pub support: bool,
    /// TRUE => national, FALSE => international
    #[serde(rename = "nationalTrip")]
    pub national_trip: bool,
    /// Textual information about the first delay on the route
    #[serde(rename = "delay")]
    pub delay: String,
    /// Textual information about the travel time on the route
    #[serde(rename = "travelTime")]
    pub travel_time: String,
    /// Vehicle standard code.
    #[serde(rename = "vehicleStandard")]
    pub vehicle_standard: String,
}

impl SroRoute {
    pub fn new(
        id: String,
        departure_station_id: i64,
        departure_time: String,
        arrival_time: String,
        vehicle_types: Vec<models::VehicleType>,
        price_from: f64,
        price_to: f64,
        notices: bool,
        support: bool,
        national_trip: bool,
        delay: String,
        travel_time: String,
        vehicle_standard: String,
    ) -> SroRoute {
        SroRoute {
            id,
            departure_station_id,
            departure_time,
            arrival_station_id: None,
            arrival_time,
            vehicle_types,
            transfers_count: None,
            price_from,
            price_to,
            prices_count: None,
            notices,
            support,
            national_trip,
            delay,
            travel_time,
            vehicle_standard,
        }
    }
}
