/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Superzone : Super zone contains one or more zones.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Superzone {
    /// Superzone localized name intended to be shown in user interface.
    #[serde(rename = "name")]
    pub name: String,
    /// Superzone city description
    #[serde(rename = "description")]
    pub description: String,
    /// List of zones in this superzone.
    #[serde(rename = "zones")]
    pub zones: Vec<models::Zone>,
}

impl Superzone {
    /// Super zone contains one or more zones.
    pub fn new(name: String, description: String, zones: Vec<models::Zone>) -> Superzone {
        Superzone {
            name,
            description,
            zones,
        }
    }
}
