/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeTicketConditions {
    /// Time to cancel ticket
    #[serde(rename = "cancel")]
    pub cancel: String,
    /// The time when ticket expires
    #[serde(rename = "expireAt")]
    pub expire_at: String,
}

impl TimeTicketConditions {
    pub fn new(cancel: String, expire_at: String) -> TimeTicketConditions {
        TimeTicketConditions { cancel, expire_at }
    }
}
