/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Timetable {
    /// Timetable ID
    #[serde(rename = "timetableId", skip_serializing_if = "Option::is_none")]
    pub timetable_id: Option<i64>,
    /// Connection ID
    #[serde(rename = "connectionId")]
    pub connection_id: i64,
    /// Departure city
    #[serde(rename = "fromCityName")]
    pub from_city_name: String,
    /// Arrival city
    #[serde(rename = "toCityName")]
    pub to_city_name: String,
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    #[serde(rename = "validTo", skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<String>,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Direction>,
    /// Timecodes used in this timetable
    #[serde(rename = "timeCodes", skip_serializing_if = "Option::is_none")]
    pub time_codes: Option<Vec<f64>>,
    /// Symbols used in this timetable
    #[serde(rename = "symbols", skip_serializing_if = "Option::is_none")]
    pub symbols: Option<Vec<String>>,
    /// Type and code of the connection
    #[serde(rename = "connectionCode")]
    pub connection_code: String,
    #[serde(rename = "carrierId", skip_serializing_if = "Option::is_none")]
    pub carrier_id: Option<i64>,
    /// Individual stations (including metadata) sort according to order which connection builds.
    #[serde(rename = "stations")]
    pub stations: Vec<models::TimetableStation>,
}

impl Timetable {
    pub fn new(
        connection_id: i64,
        from_city_name: String,
        to_city_name: String,
        connection_code: String,
        stations: Vec<models::TimetableStation>,
    ) -> Timetable {
        Timetable {
            timetable_id: None,
            connection_id,
            from_city_name,
            to_city_name,
            valid_from: None,
            valid_to: None,
            direction: None,
            time_codes: None,
            symbols: None,
            connection_code,
            carrier_id: None,
            stations,
        }
    }
}
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Direction {
    #[serde(rename = "there")]
    #[default]
    There,
    #[serde(rename = "back")]
    Back,
}
