/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopUpAndChargeCreditRequest : Top up and charge account credit request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopUpAndChargeCreditRequest {
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "paymentMethodCode")]
    pub payment_method_code: String,
    #[serde(rename = "correlationId")]
    pub correlation_id: String,
    #[serde(rename = "rememberCard", skip_serializing_if = "Option::is_none")]
    pub remember_card: Option<bool>,
    #[serde(rename = "formFields")]
    pub form_fields: Vec<models::PaymentFormFieldValue>,
    #[serde(rename = "tickets", skip_serializing_if = "Option::is_none")]
    pub tickets: Option<Vec<models::PaymentTicketRequest>>,
}

impl TopUpAndChargeCreditRequest {
    /// Top up and charge account credit request
    pub fn new(
        amount: f64,
        currency: models::Currency,
        payment_method_code: String,
        correlation_id: String,
        form_fields: Vec<models::PaymentFormFieldValue>,
    ) -> TopUpAndChargeCreditRequest {
        TopUpAndChargeCreditRequest {
            amount,
            currency,
            payment_method_code,
            correlation_id,
            remember_card: None,
            form_fields,
            tickets: None,
        }
    }
}
