/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};


/// struct for typed errors of method [`get_time_ticket_price`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTimeTicketPriceError {
    Status400(crate::models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


pub async fn get_time_ticket_price(configuration: &configuration::Configuration, from_station_id: i64, to_station_id: i64, time_ticket_type: &str, valid_from: &str, tariff: &str, x_currency: Option<&str>) -> Result<Vec<crate::models::TimeTicketPrice>, Error<GetTimeTicketPriceError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/pricelists/timeticket/{fromStationId}/{toStationId}/{timeTicketType}/{validFrom}/{tariff}", local_var_configuration.base_path, fromStationId=from_station_id, toStationId=to_station_id, timeTicketType=crate::apis::urlencode(time_ticket_type), validFrom=crate::apis::urlencode(valid_from), tariff=crate::apis::urlencode(tariff));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_currency {
        local_var_req_builder = local_var_req_builder.header("X-Currency", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetTimeTicketPriceError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

