/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllowedPaymentDefinition {
    /// Payment method identifier
    #[serde(rename = "paymentType")]
    pub payment_type: String,
    #[serde(rename = "currencyDefinitions")]
    pub currency_definitions: Vec<models::CurrencyDefinition>,
}

impl AllowedPaymentDefinition {
    pub fn new(
        payment_type: String,
        currency_definitions: Vec<models::CurrencyDefinition>,
    ) -> AllowedPaymentDefinition {
        AllowedPaymentDefinition {
            payment_type,
            currency_definitions,
        }
    }
}
