/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Carrier {
    #[serde(rename = "carrierId")]
    pub carrier_id: i64,
    /// Informace o dopravci
    #[serde(rename = "carrierInfo")]
    pub carrier_info: String,
}

impl Carrier {
    pub fn new(carrier_id: i64, carrier_info: String) -> Carrier {
        Carrier {
            carrier_id,
            carrier_info,
        }
    }
}
