/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Company {
    #[serde(rename = "companyName")]
    pub company_name: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "registrationNumber")]
    pub registration_number: String,
    #[serde(rename = "vatNumber", skip_serializing_if = "Option::is_none")]
    pub vat_number: Option<String>,
}

impl Company {
    pub fn new(company_name: String, address: String, registration_number: String) -> Company {
        Company {
            company_name,
            address,
            registration_number,
            vat_number: None,
        }
    }
}


