/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUnregisteredTicketRequest {
    /// Agree with terms
    #[serde(rename = "agreeWithTerms")]
    pub agree_with_terms: bool,
    #[serde(rename = "ticketRequests")]
    pub ticket_requests: Vec<models::CreateTicketRequest>,
    /// Optional code of an affiliate partner.
    #[serde(rename = "affiliateCode", skip_serializing_if = "Option::is_none")]
    pub affiliate_code: Option<String>,
}

impl CreateUnregisteredTicketRequest {
    pub fn new(
        agree_with_terms: bool,
        ticket_requests: Vec<models::CreateTicketRequest>,
    ) -> CreateUnregisteredTicketRequest {
        CreateUnregisteredTicketRequest {
            agree_with_terms,
            ticket_requests,
            affiliate_code: None,
        }
    }
}
