/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUnregisteredTimeTicketRequest {
    #[serde(rename = "unregisteredTimeTicketCreateRequest")]
    pub unregistered_time_ticket_create_request: Vec<models::UnregisteredTimeTicketCreateRequest>,
}

impl CreateUnregisteredTimeTicketRequest {
    pub fn new(
        unregistered_time_ticket_create_request: Vec<models::UnregisteredTimeTicketCreateRequest>,
    ) -> CreateUnregisteredTimeTicketRequest {
        CreateUnregisteredTimeTicketRequest {
            unregistered_time_ticket_create_request,
        }
    }
}
