/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscountState : * `VALID` - Valid discount * `USED` - Invalid (used) discount * `EXPIRED` - Invalid (expired) discount
/// * `VALID` - Valid discount * `USED` - Invalid (used) discount * `EXPIRED` - Invalid (expired) discount
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum DiscountState {
    #[serde(rename = "VALID")]
    #[default]
    Valid,
    #[serde(rename = "USED")]
    Used,
    #[serde(rename = "EXPIRED")]
    Expired,
}

impl std::fmt::Display for DiscountState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Valid => write!(f, "VALID"),
            Self::Used => write!(f, "USED"),
            Self::Expired => write!(f, "EXPIRED"),
        }
    }
}
