/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Discount {
    #[serde(rename = "id")]
    pub id: i64,
    /// Percentual discount size
    #[serde(rename = "percentage")]
    pub percentage: i32,
    /// Maximal number of passengers
    #[serde(rename = "passengers")]
    pub passengers: i32,
    /// Default country/city/station translation
    #[serde(rename = "fromLocation", skip_serializing_if = "Option::is_none")]
    pub from_location: Option<String>,
    /// Default arrival country/city/station translations
    #[serde(rename = "toLocation", skip_serializing_if = "Option::is_none")]
    pub to_location: Option<String>,
    #[serde(rename = "dateFrom", skip_serializing_if = "Option::is_none")]
    pub date_from: Option<String>,
    #[serde(rename = "dateTo", skip_serializing_if = "Option::is_none")]
    pub date_to: Option<String>,
    #[serde(rename = "state")]
    pub state: crate::models::DiscountState,
    /// If there is used discount there is as well ticket ID which is linked to it.
    #[serde(rename = "ticketId", skip_serializing_if = "Option::is_none")]
    pub ticket_id: Option<i64>,
}

impl Discount {
    pub fn new(id: i64, percentage: i32, passengers: i32, state: crate::models::DiscountState) -> Discount {
        Discount {
            id,
            percentage,
            passengers,
            from_location: None,
            to_location: None,
            date_from: None,
            date_to: None,
            state,
            ticket_id: None,
        }
    }
}


