/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForgottenPasswordByMailRequest {
    #[serde(rename = "email")]
    pub email: String,
    /// Attribute value will be added into URL address as path param
    #[serde(rename = "correlationId", skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
}

impl ForgottenPasswordByMailRequest {
    pub fn new(email: String) -> ForgottenPasswordByMailRequest {
        ForgottenPasswordByMailRequest {
            email,
            correlation_id: None,
        }
    }
}
