/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IntegratedTransportSystem : Integrated transport system - ITS (IDS in Czech). Root object of the object graph (tree) describing whole ITS.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegratedTransportSystem {
    /// ITS name as a localized string intended to be shown in user interface.
    #[serde(rename = "name")]
    pub name: String,
    /// ITS description as a localized string intended to be shown in user interface.
    #[serde(rename = "description")]
    pub description: String,
    /// List of super zones in this ITS.
    #[serde(rename = "superZones")]
    pub super_zones: Vec<models::Superzone>,
}

impl IntegratedTransportSystem {
    /// Integrated transport system - ITS (IDS in Czech). Root object of the object graph (tree) describing whole ITS.
    pub fn new(
        name: String,
        description: String,
        super_zones: Vec<models::Superzone>,
    ) -> IntegratedTransportSystem {
        IntegratedTransportSystem {
            name,
            description,
            super_zones,
        }
    }
}
