/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct News {
    #[serde(rename = "discounts", skip_serializing_if = "Option::is_none")]
    pub discounts: Option<Vec<crate::models::NewsDiscounts>>,
    #[serde(rename = "promotions", skip_serializing_if = "Option::is_none")]
    pub promotions: Option<Vec<crate::models::NewsPromotions>>,
    #[serde(rename = "news", skip_serializing_if = "Option::is_none")]
    pub news: Option<Vec<crate::models::NewsNews>>,
}

impl News {
    pub fn new() -> News {
        News {
            discounts: None,
            promotions: None,
            news: None,
        }
    }
}


