/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderedAddon {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "iconUrl")]
    pub icon_url: String,
    #[serde(rename = "infoUrl", skip_serializing_if = "Option::is_none")]
    pub info_url: Option<String>,
    #[serde(rename = "infoUrlLabel", skip_serializing_if = "Option::is_none")]
    pub info_url_label: Option<String>,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "conditions")]
    pub conditions: Box<models::PriceConditions>,
}

impl OrderedAddon {
    pub fn new(
        id: i64,
        name: String,
        description: String,
        icon_url: String,
        price: f64,
        currency: models::Currency,
        conditions: models::PriceConditions,
    ) -> OrderedAddon {
        OrderedAddon {
            id,
            name,
            description,
            icon_url,
            info_url: None,
            info_url_label: None,
            price,
            currency,
            conditions: Box::new(conditions),
        }
    }
}
