/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PassengerChangeResponse : Result of customer change request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PassengerChangeResponse {
    /// User information change charge (in ticket currency)
    #[serde(rename = "charge", skip_serializing_if = "Option::is_none")]
    pub charge: Option<f64>,
}

impl PassengerChangeResponse {
    /// Result of customer change request
    pub fn new() -> PassengerChangeResponse {
        PassengerChangeResponse { charge: None }
    }
}
