/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

/// PaymentFormFieldType : Valid field types required for payment form.

/// Valid field types required for payment form.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentFormFieldType {
    #[serde(rename = "EMAIL")]
    EMAIL,
    #[serde(rename = "FIRST_NAME")]
    FIRSTNAME,
    #[serde(rename = "SURNAME")]
    SURNAME,
    #[serde(rename = "PASSWORD")]
    PASSWORD,
    #[serde(rename = "PASSWORD_CONFIRMATION")]
    PASSWORDCONFIRMATION,

}

impl ToString for PaymentFormFieldType {
    fn to_string(&self) -> String {
        match self {
            Self::EMAIL => String::from("EMAIL"),
            Self::FIRSTNAME => String::from("FIRST_NAME"),
            Self::SURNAME => String::from("SURNAME"),
            Self::PASSWORD => String::from("PASSWORD"),
            Self::PASSWORDCONFIRMATION => String::from("PASSWORD_CONFIRMATION"),
        }
    }
}

impl Default for PaymentFormFieldType {
    fn default() -> PaymentFormFieldType {
        Self::EMAIL
    }
}




