/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentTicketType {
    #[serde(rename = "RJ_SEAT")]
    #[default]
    RjSeat,
    #[serde(rename = "RJ_TIME")]
    RjTime,
    #[serde(rename = "RJ_SRO")]
    RjSro,
}

impl std::fmt::Display for PaymentTicketType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RjSeat => write!(f, "RJ_SEAT"),
            Self::RjTime => write!(f, "RJ_TIME"),
            Self::RjSro => write!(f, "RJ_SRO"),
        }
    }
}
