/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

/// PercentualDiscount : Percentual discount



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PercentualDiscount {
    #[serde(rename = "id")]
    pub id: i64,
    /// Size of a percentual discount
    #[serde(rename = "percentage")]
    pub percentage: i32,
    /// Discount sum in account currency
    #[serde(rename = "amount")]
    pub amount: f32,
    /// Maximal number of passengers
    #[serde(rename = "passengers")]
    pub passengers: i32,
    /// Default departure country/city/station translations
    #[serde(rename = "fromLocation", skip_serializing_if = "Option::is_none")]
    pub from_location: Option<String>,
    /// Default arrival country/city/station translations
    #[serde(rename = "toLocation", skip_serializing_if = "Option::is_none")]
    pub to_location: Option<String>,
    #[serde(rename = "dateFrom", skip_serializing_if = "Option::is_none")]
    pub date_from: Option<String>,
    #[serde(rename = "dateTo", skip_serializing_if = "Option::is_none")]
    pub date_to: Option<String>,
}

impl PercentualDiscount {
    /// Percentual discount
    pub fn new(id: i64, percentage: i32, amount: f32, passengers: i32) -> PercentualDiscount {
        PercentualDiscount {
            id,
            percentage,
            amount,
            passengers,
            from_location: None,
            to_location: None,
            date_from: None,
            date_to: None,
        }
    }
}


