/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SeatClass {
    /// enum.name
    #[serde(rename = "key")]
    pub key: String,
    /// Class title
    #[serde(rename = "title")]
    pub title: String,
    /// Class descriptions.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "imageUrl", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Class photogalery URL
    #[serde(rename = "galleryUrl", skip_serializing_if = "Option::is_none")]
    pub gallery_url: Option<String>,
}

impl SeatClass {
    pub fn new(key: String, title: String, description: String) -> SeatClass {
        SeatClass {
            key,
            title,
            description,
            image_url: None,
            gallery_url: None,
        }
    }
}


