/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectedAddon {
    #[serde(rename = "addonId")]
    pub addon_id: i64,
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    /// Hash (MD5) of cancellation terms, agreed on by the customer
    #[serde(rename = "conditionsHash")]
    pub conditions_hash: String,
}

impl SelectedAddon {
    pub fn new(
        addon_id: i64,
        count: i32,
        price: f64,
        currency: models::Currency,
        conditions_hash: String,
    ) -> SelectedAddon {
        SelectedAddon {
            addon_id,
            count,
            price,
            currency,
            conditions_hash,
        }
    }
}
