/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SimpleRegisteredAccountRequest {
    #[serde(rename = "firstName")]
    pub first_name: String,
    #[serde(rename = "surname")]
    pub surname: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "notifications")]
    pub notifications: Box<crate::models::Notifications>,
    /// Agree with terms
    #[serde(rename = "agreeWithTerms")]
    pub agree_with_terms: bool,
}

impl SimpleRegisteredAccountRequest {
    pub fn new(first_name: String, surname: String, email: String, password: String, notifications: crate::models::Notifications, agree_with_terms: bool) -> SimpleRegisteredAccountRequest {
        SimpleRegisteredAccountRequest {
            first_name,
            surname,
            email,
            phone_number: None,
            password,
            notifications: Box::new(notifications),
            agree_with_terms,
        }
    }
}


