/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SroTicketRequest {
    #[serde(rename = "routeId")]
    pub route_id: String,
    #[serde(rename = "priceSourceId")]
    pub price_source_id: String,
    #[serde(rename = "seatClass")]
    pub seat_class: String,
    #[serde(rename = "sections")]
    pub sections: Vec<models::SroTicketSections>,
    #[serde(rename = "passengers")]
    pub passengers: Vec<models::SroTicketPassenger>,
}

impl SroTicketRequest {
    pub fn new(
        route_id: String,
        price_source_id: String,
        seat_class: String,
        sections: Vec<models::SroTicketSections>,
        passengers: Vec<models::SroTicketPassenger>,
    ) -> SroTicketRequest {
        SroTicketRequest {
            route_id,
            price_source_id,
            seat_class,
            sections,
            passengers,
        }
    }
}
