/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TicketBill {
    #[serde(rename = "amount")]
    pub amount: f32,
    #[serde(rename = "currency")]
    pub currency: crate::models::Currency,
    #[serde(rename = "label")]
    pub label: String,
}

impl TicketBill {
    pub fn new(amount: f32, currency: crate::models::Currency, label: String) -> TicketBill {
        TicketBill {
            amount,
            currency,
            label,
        }
    }
}


