/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

/// TimeTicketCustomerAction : Defines which actions can be executed with current time ticket state



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TimeTicketCustomerAction {
    #[serde(rename = "showDetail")]
    pub show_detail: bool,
    #[serde(rename = "pay")]
    pub pay: bool,
    #[serde(rename = "payRemaining")]
    pub pay_remaining: bool,
    #[serde(rename = "cancel")]
    pub cancel: bool,
    #[serde(rename = "storno")]
    pub storno: bool,
    #[serde(rename = "sentToMail")]
    pub sent_to_mail: bool,
    #[serde(rename = "printTicket")]
    pub print_ticket: bool,
    #[serde(rename = "printInvoice")]
    pub print_invoice: bool,
    #[serde(rename = "showQr")]
    pub show_qr: bool,
}

impl TimeTicketCustomerAction {
    /// Defines which actions can be executed with current time ticket state
    pub fn new(show_detail: bool, pay: bool, pay_remaining: bool, cancel: bool, storno: bool, sent_to_mail: bool, print_ticket: bool, print_invoice: bool, show_qr: bool) -> TimeTicketCustomerAction {
        TimeTicketCustomerAction {
            show_detail,
            pay,
            pay_remaining,
            cancel,
            storno,
            sent_to_mail,
            print_ticket,
            print_invoice,
            show_qr,
        }
    }
}


