/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimetableStation {
    /// Station ID used for search in locations
    #[serde(rename = "stationId")]
    pub station_id: i64,
    /// Planned station departure time (1st station in order does not have arrival time)
    #[serde(rename = "departure", skip_serializing_if = "Option::is_none")]
    pub departure: Option<String>,
    /// Planned station arrival time (1st station in order does not have arrival time)
    #[serde(rename = "arrival", skip_serializing_if = "Option::is_none")]
    pub arrival: Option<String>,
    /// Symbols used in this station
    #[serde(rename = "symbols", skip_serializing_if = "Option::is_none")]
    pub symbols: Option<Vec<String>>,
    /// Platform
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
}

impl TimetableStation {
    pub fn new(station_id: i64) -> TimetableStation {
        TimetableStation {
            station_id,
            departure: None,
            arrival: None,
            symbols: None,
            platform: None,
        }
    }
}
