/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimeTicket : Object representing time ticket
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeTicket {
    /// ID of the ticket
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "accountCode")]
    pub account_code: String,
    #[serde(rename = "ticketCode")]
    pub ticket_code: String,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "unpaid")]
    pub unpaid: f64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "surName")]
    pub sur_name: String,
    #[serde(rename = "tariff")]
    pub tariff: Box<models::Tariff>,
    #[serde(rename = "type")]
    pub r#type: models::TimeTicketType,
    #[serde(rename = "state")]
    pub state: models::TicketState,
    #[serde(rename = "seatClass")]
    pub seat_class: String,
    #[serde(rename = "conditions")]
    pub conditions: Box<models::TimeTicketConditions>,
    #[serde(
        rename = "customerNotifications",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_notifications: Option<Vec<String>>,
    #[serde(rename = "customerActions")]
    pub customer_actions: Box<models::CustomerActions>,
    #[serde(rename = "bills")]
    pub bills: Vec<models::TimeTicketBill>,
    #[serde(rename = "station1Id")]
    pub station1_id: i64,
    #[serde(rename = "station2Id")]
    pub station2_id: i64,
    #[serde(rename = "validFrom")]
    pub valid_from: String,
    #[serde(rename = "validTo")]
    pub valid_to: String,
    /// Time ticket group transaction ID
    #[serde(rename = "paymentId")]
    pub payment_id: i64,
}

impl TimeTicket {
    /// Object representing time ticket
    pub fn new(
        id: i64,
        account_code: String,
        ticket_code: String,
        price: f64,
        unpaid: f64,
        name: String,
        sur_name: String,
        tariff: models::Tariff,
        r#type: models::TimeTicketType,
        state: models::TicketState,
        seat_class: String,
        conditions: models::TimeTicketConditions,
        customer_actions: models::CustomerActions,
        bills: Vec<models::TimeTicketBill>,
        station1_id: i64,
        station2_id: i64,
        valid_from: String,
        valid_to: String,
        payment_id: i64,
    ) -> TimeTicket {
        TimeTicket {
            id,
            account_code,
            ticket_code,
            price,
            unpaid,
            name,
            sur_name,
            tariff: Box::new(tariff),
            r#type,
            state,
            seat_class,
            conditions: Box::new(conditions),
            customer_notifications: None,
            customer_actions: Box::new(customer_actions),
            bills,
            station1_id,
            station2_id,
            valid_from,
            valid_to,
            payment_id,
        }
    }
}
