/*
 * RegioJet API
 *
 * A set of endpoints to interact with RegioJet transport services. Search for connections, book tickets, see the list of served stations and more. All endpoints consume and produce JSON strings, with the exception of ticket printing (/tickets/{ticketId}/print) that produce printable HTML code.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: developers@studentagency.cz
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Zone : Zone within the context of Integrated Transport System. It affects tarrif (price) of the ticket.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Zone {
    /// Name of zone as a localized string intended to be shown in user interface.
    #[serde(rename = "name")]
    pub name: String,
    /// Zone city description
    #[serde(rename = "description")]
    pub description: String,
}

impl Zone {
    /// Zone within the context of Integrated Transport System. It affects tarrif (price) of the ticket.
    pub fn new(name: String, description: String) -> Zone {
        Zone { name, description }
    }
}
